Repository perfectsense/gyro-aws-provider, pull requests merged in 2021-09, with the labels that each got.

#520 Update changelog with 1.4.1 and 1.4.2 patch updates
  CHANGELOG.md
Labels: Documentation

#527 Bump gyro core version to 1.1.2
  build.gradle
Labels: enhancement

#528 Update changelog to reflect patch 1.4.3
  CHANGELOG.md
Labels: release
