Repository perfectsense/gyro-aws-provider, pull requests merged in 2021-06, with the labels that each got.

#473 Prepare for release 1.2.0
  CHANGELOG.md
  README.md
  build.gradle
  src/main/java/gyro/aws/package-info.java
Labels: release

#474 Prepare for development of version 1.2.1
  build.gradle
Labels: release

#486 Prepare for development of version 1.2.2
  build.gradle
Labels: release

#487 Add support for gp3 volume type on block device mappings
  src/main/java/gyro/aws/ec2/BlockDeviceMapping.java
Labels: enhancement

#488 Allow "CUSTOM" ami type for node groups
  src/main/java/gyro/aws/eks/EksNodegroupResource.java
Labels: enhancement

#492 Prepare for release 1.2.2
  CHANGELOG.md
Labels: priority:high, release

#493 Prepare for development of version 1.2.3
  build.gradle
Labels: release
